---
- name: Install BorgBackup & Perform Backup Duty
  hosts: all
  become: yes
  tasks:
    # Install BorgBackup
    - name: Install BorgBackup (Ubuntu/Debian)
      apt:
        name: borgbackup
        state: present
      when: ansible_facts['distribution'] == 'Ubuntu' or ansible_facts['distribution'] == 'Debian'

    - name: Install BorgBackup (CentOS/RedHat)
      yum:
        name: borgbackup
        state: present
      when: ansible_facts['distribution'] == 'CentOS' or ansible_facts['distribution'] == 'RedHat'



