services:
  sftp:
    container_name: sftp
    image: atmoz/sftp:latest
    restart: no
    volumes:
      - ./tests/sftp:/home/example/upload
    command: example:1234:::upload
    networks:
      - app
  postgresql:
    container_name: postgresql
    image: postgres:latest
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: bckupmgr
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./tests/postgresql_init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./tests/mysql_init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app
  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: test
    volumes:
      - ./tests/mongodb-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    networks:
      - app
  ubuntu:
    container_name: ubuntu
    image: ubuntu:latest
    command: ['bash', '/root/start_ubuntu.sh' ]
    volumes:
      - ./tests/start_ubuntu.sh:/root/start_ubuntu.sh
    networks:
      - app
  app:
    container_name: app
    restart: no
    build:
      context: .
    environment:
      HAWKUPS_LOG_LEVEL: DEBUG
    volumes:
      - ./tests/app/config:/config
      - ./tests/app/log:/log
      - ./tests/app/tmp:/tmp
      - ./tests/app/backups:/backups
    ports:
      - 5000:5000
    networks:
      - app
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://localhost:5000/api/health' ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 1s

networks:
  app:
