services:
  sftp:
    container_name: sftp
    image: atmoz/sftp:latest
    restart: no
    volumes:
      - ./tests/sftp:/home/example/upload
    command: example:1234:::upload
    networks:
      - app
  postgresql:
    container_name: postgresql
    image: postgres:latest
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: bckupmgr
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./tests/postgresql_init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./tests/mysql_init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app
  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: test
    volumes:
      - ./tests/mongodb-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    networks:
      - app
  ubuntu:
    container_name: ubuntu
    image: ${LOCAL_ACR_URL}/ubuntu-with-ssh:latest
    environment:
      SSH_USERNAME: root
      SSH_PASSWORD: 1234
    networks:
      - app
  redis:
    container_name: redis
    image: redis:latest
    networks:
      - app
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
      interval: 5s
      timeout: 5s
      retries: 3
  app:
    container_name: app
    restart: no
    build:
      context: .
    environment:
      REDIS_SERVER: redis:6379
      LOG_LEVEL: DEBUG
      API_TOKEN: unsecure_api_token
      PROMETHEUS: true
      API_DOCS: true
    ports:
      - 5000:5000
    volumes:
      - ./tests/app/data:/data
    depends_on:
      - redis
    networks:
      - app
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://localhost:5000/api/health' ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 1s
  worker:
    container_name: worker
    restart: no
    build:
      context: .
    command: celery -A app worker --loglevel=DEBUG --concurrency=4
    environment:
      REDIS_SERVER: redis:6379
      LOG_LEVEL: DEBUG
      API_TOKEN: unsecure_api_token
    volumes:
      - ./tests/app/data:/data
      - ./tests/app/log:/log
      - ./tests/app/tmp:/tmp
      - ./tests/app/backups:/backups
    depends_on:
      - redis
    networks:
      - app
    healthcheck:
      test: [ 'CMD', 'celery', '-A', 'app', 'status']
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 1s

networks:
  app:
