system:
  prometheus:
    enabled: true
    port: 9100

alerts:
  - name: example-webhook-alert
    success: false
    failure: true
    webhook:
      url: https://api.pushover.net/1/messages.json
      data:
        user: user_key_here # or environment variable: HAWKUPS_ALERTS__example_webhook_alert__USER
        token: api_token_here # or environment variable: HAWKUPS_ALERTS__example_webhook_alert__TOKEN
  - name: example-pushover-alert
    success: false
    failure: true
    notifiers:
      type: pushover
      data:
        user: user_key_here # or environment variable: HAWKUPS_ALERTS__example_webhook_alert__USER
        token: api_token_here # or environment variable: HAWKUPS_ALERTS__example_webhook_alert__TOKEN

destinations:
  - name: example-sftp-server
    sftp:
      server: sftp
      port: 22
      username: example
      password: 1234 # or environment variable: HAWKUPS_DESTINATIONS__example_sftp_server__PASSWORD
      path: /upload
    retention: 7d
  - name: example-local-server
    local: {}
    retention: 7d
  # - name: example-smb-server
  #   smb:
  #     server: smb
  #     port: 445
  #     username: example
  #     password: 1234 # or environment variable: HAWKUPS_DESTINATIONS__example_smb_server__PASSWORD
  #     path: /upload
  #   retention: 7d

jobs:
  - name: example-podb-server
    postgresql:
      server: postgresql
      port: 5432
      username: bckupmgr
      password: 1234 # or environment variable: HAWKUPS_JOBS__example_podb_server__PASSWORD
      ssl: disable
      excludes: []
    destination: example-sftp-server
    retention: 2d
    alert: example-webhook-alert
  - name: example-mydb-server
    mysql:
      server: mysql
      port: 3306
      username: root
      password: 1234 # or environment variable: HAWKUPS_JOBS__example_mydb_server__PASSWORD
      excludes: []
    destination: example-sftp-server # example-smb-server
    alert: example-webhook-alert
  - name: example-modb-server
    mongodb:
      server: mongodb
      port: 27017
      username: root
      password: 1234 # or environment variable: HAWKUPS_JOBS__example_modb_server__PASSWORD
      excludes: []
    destination: example-local-server
    alert: example-webhook-alert
  - name: example-files-host
    files:
      host: ubuntu
      port: 22
      username: root
      password: 1234 # or environment variable: HAWKUPS_JOBS__example_files_hosts__PASSWORD
      paths:
        - /home/example
        - /var/log/lastlog
    destination: example-local-server
    alert: example-webhook-alert
