FROM ubuntu:latest

# Setup
RUN apt-get update && apt-get install -y openssh-server
RUN mkdir /var/run/sshd
RUN echo 'root:1234' | chpasswd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# Start
EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
