name: Build/Push & Test App for Development
on:
  push:
    branches:
      - 'dev/v[0-9]+.[0-9]+'

env:
  DOCKER_HOST: "tcp://docker:2376/"
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "/certs/client"
  IMAGE_BASE: ${{ vars.LOCAL_ACR_URL }}/${{ vars.LOCAL_ACR_USERNAME }}
  UBUNTU_VERSION: 24.04

jobs:
  # https://forum.gitea.com/t/act-runner-in-k8s-fail-to-connect-to-docker-daemon/8736/16
  release:
    name: Release (linux/${{ matrix.architecture }})
    runs-on: buildx-ubuntu-latest
    container:
      image: gitea/runner-images:ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Get Meta
        id: meta
        run: |
          echo REPO_NAME=$(echo ${GITHUB_REPOSITORY} | awk -F"/" '{print $2}') >> $GITHUB_OUTPUT
          echo REPO_VERSION=$(echo ${GITHUB_REF} | awk -F"/" '{print $4}') >> $GITHUB_OUTPUT
          echo BUILD_NUMBER=$(echo "`date +'%Y%m%d'`.${{ github.run_number }}") >> $GITHUB_OUTPUT

      - name: Install QEMU
        run: |
          sudo apt-get update
          sudo apt-get install qemu-user-static -y

      - name: Setup Docker Context for Buildx
        run: |
          docker context create builders

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          builder: builders

      - name: Login to Local ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.LOCAL_ACR_URL }}
          username: ${{ vars.LOCAL_ACR_USERNAME }}
          password: ${{ secrets.LOCAL_ACR_PASSWORD }}

      - name: Build & Push to Local ACR
        uses: docker/build-push-action@v6
        with:
          platforms: linux/${{ matrix.architecture }}
          push: true
          build-args: |
            OS_VERSION=${{ env.UBUNTU_VERSION }}
            ARCH=${{ matrix.architecture }}
          tags: |
            ${{ env.IMAGE_BASE }}/${{ steps.meta.outputs.REPO_NAME }}:${{ steps.meta.outputs.REPO_VERSION }}-${{ steps.meta.outputs.BUILD_NUMBER }}
            ${{ env.IMAGE_BASE }}/${{ steps.meta.outputs.REPO_NAME }}:dev-latest

  tests:
    name: Tests
    runs-on: buildx-ubuntu-latest
    container:
      image: gitea/runner-images:ubuntu-latest
    needs: release
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Get Meta
        id: meta
        run: |
          echo REPO_NAME=$(echo ${GITHUB_REPOSITORY} | awk -F"/" '{print $2}') >> $GITHUB_OUTPUT
          echo REPO_VERSION=$(echo ${GITHUB_REF} | awk -F"/" '{print $4}') >> $GITHUB_OUTPUT
          echo BUILD_NUMBER=$(echo "`date +'%Y%m%d'`.${{ github.run_number }}") >> $GITHUB_OUTPUT
      
      - name: Start containers
        run: |
          export REPO_NAME=${{ steps.meta.outputs.REPO_NAME }}
          export IMAGE_VERSION=${{ steps.meta.outputs.REPO_VERSION }}-${{ steps.meta.outputs.BUILD_NUMBER }}
          docker compose -f tests/docker-compose.yml rm -fsv
          docker compose -f tests/docker-compose.yml up -d --build --remove-orphans

          apt install net-tools
          netstat -lntu

      - name: Run Tests
        id: status
        env:
          DISPLAY: ''
        run: |
          python3 -m venv .venv
          . .venv/bin/activate
          python3 -m pip install --upgrade pip
          python3 -m pip install requests
          python3 tests/test.py
          deactivate

      - name: Stop if Tests Failed
        if: steps.test_status.outputs.results != 'success'
        run: |
          echo "Tests failed! Please view logs for reason."
      
      - name: Cleanup containers
        if: always()
        run: |
          docker compose -f tests/docker-compose.yml down --remove-orphans
          docker compose -f tests/docker-compose.yml rm

  report:
    name: Report
    runs-on: ubuntu-latest
    continue-on-error: true
    needs:
      - release
      - tests
    # uses: adam/gitea-workflows/.gitea/workflows/notify.yaml@main
    steps:
      - name: Get Meta
        id: meta
        run: |
          echo REPO_NAME=$(echo ${GITHUB_REPOSITORY} | awk -F"/" '{print $2}') >> $GITHUB_OUTPUT
          echo REPO_VERSION=$(echo ${GITHUB_REF} | awk -F"/" '{print $4}') >> $GITHUB_OUTPUT
          echo BUILD_NUMBER=$(echo "`date +'%Y%m%d'`.${{ github.run_number }}") >> $GITHUB_OUTPUT

      - name: Report of Success
        if: needs.release.result == 'success' && needs.tests.result == 'success'
        uses: umahmood/pushover-actions@main
        env:
          PUSHOVER_USER: ${{ secrets.PUSHOVER_USER }}
          PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
        with:
          title: Gitea DevOps
          message: ✅ Built/Pushed & Tested ${{ steps.meta.outputs.REPO_NAME }}:${{ steps.meta.outputs.REPO_VERSION }}-${{ steps.meta.outputs.BUILD_NUMBER }} app!

      - name: Report of Failure
        if: needs.release.result != 'success' || needs.tests.result != 'success'
        uses: umahmood/pushover-actions@main
        env:
          PUSHOVER_USER: ${{ secrets.PUSHOVER_USER }}
          PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
        with:
          title: Gitea DevOps
          message: ❌ Unable to build/push & test ${{ steps.meta.outputs.REPO_NAME }}:${{ steps.meta.outputs.REPO_VERSION }}-${{ steps.meta.outputs.BUILD_NUMBER }} app.
