name: Build/Push & Test App
on:
  push:
    branches:
      - 'dev/v[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Local ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.LOCAL_ACR_URL }}
          username: ${{ vars.LOCAL_ACR_USERNAME }}
          password: ${{ secrets.LOCAL_ACR_PASSWORD }}
          
      - name: Get Meta
        id: meta
        run: |
          echo REPO_NAME=$(echo ${GITHUB_REPOSITORY} | awk -F"/" '{print $2}') >> $GITHUB_OUTPUT
          echo REPO_VERSION=$(echo ${GITHUB_REF} | awk -F"/" '{print $4}') >> $GITHUB_OUTPUT
          echo BUILD_NUMBER=$(echo "`date +'%Y%m%d'`.${{ github.run_number }}") >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push to Local ACR
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          tags: |
            ${{ vars.LOCAL_ACR_URL }}/${{ steps.meta.outputs.REPO_NAME }}:${{ steps.meta.outputs.REPO_VERSION }}-${{ steps.meta.outputs.BUILD_NUMBER }}

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Start Services & App
        env:
          HAWKUPS_ALERTS__example_webhook_alert__USER: ${{ secrets.HAWKUPS_PUSHOVER_USER }}
          HAWKUPS_ALERTS__example_webhook_alert__TOKEN: ${{ secrets.HAWKUPS_PUSHOVER_TOKEN }}
          HAWKUPS_ALERTS__example_pushover_alert__USER: ${{ secrets.HAWKUPS_PUSHOVER_USER }}
          HAWKUPS_ALERTS__example_pushover_alert__TOKEN: ${{ secrets.HAWKUPS_PUSHOVER_TOKEN }}
        run: bash local_run.sh
      
      - name: Get Health Check via API
        id: api_health_check
        uses: muhfaris/request-action@v1
        with:
          url: http://localhost:5000/api/health
          method: GET

      - name: Validate App Health Check API Call
        if: steps.api_health_check.outputs.response-status != 200
        run: |
          echo "App health check (/api/health) returned ${{ steps.api_health_check.outputs.response-status }} HTTP code! Output: \n${{ steps.api_health_check.outputs.response-data }}"
          exit 1

      - name: Pull List of Alerts via API
        id: api_alerts
        uses: muhfaris/request-action@v1
        with:
          url: http://localhost:5000/api/alerts
          method: GET

      - name: Validate List of Alerts API Call
        if: steps.api_alerts.outputs.response-status != 200
        run: |
          echo "App health check (/api/alerts) returned ${{ steps.api_alerts.outputs.response-status }} HTTP code! Output: \n${{ steps.api_alerts.outputs.response-data }}"
          exit 1

      - name: Pull List of Jobs via API
        id: api_jobs
        uses: muhfaris/request-action@v1
        with:
          url: http://localhost:5000/api/jobs
          method: GET

      - name: Validate List of Jobs API Call
        if: steps.api_jobs.outputs.response-status != 200
        run: |
          echo "App health check (/api/alerts) returned ${{ steps.api_jobs.outputs.response-status }} HTTP code! Output: \n${{ steps.api_jobs.outputs.response-data }}"
          exit 1

      # - name: [API] Test Alerts

      # - name: [API] Test Jobs

  notify:
    runs-on: ubuntu-latest
    if: job.status == 'success'
    needs:
      - release
      - tests
    steps:
      - name: Get Meta
        id: meta
        run: |
          echo REPO_NAME=$(echo ${GITHUB_REPOSITORY} | awk -F"/" '{print $2}') >> $GITHUB_OUTPUT
          echo REPO_VERSION=$(echo ${GITHUB_REF} | awk -F"/" '{print $4}') >> $GITHUB_OUTPUT
          echo BUILD_NUMBER=$(echo "`date +'%Y%m%d'`.${{ github.run_number }}") >> $GITHUB_OUTPUT

      - name: Notify Developer of Success
        if: job.status == 'success'
        uses: umahmood/pushover-actions@main
        env:
          PUSHOVER_USER: ${{ secrets.PUSHOVER_USER }}
          PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
        with:
          title: Gitea DevOps
          message: ✅ Built/Pushed & Tested ${{ steps.meta.outputs.REPO_NAME }}:${{ steps.meta.outputs.REPO_VERSION }}-${{ steps.meta.outputs.BUILD_NUMBER }} app!

      - name: Notify Developer of Failure
        if: job.status != 'success'
        uses: umahmood/pushover-actions@main
        env:
          PUSHOVER_USER: ${{ secrets.PUSHOVER_USER }}
          PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
        with:
          title: Gitea DevOps
          message: ❌ Unable to build/push & test ${{ steps.meta.outputs.REPO_NAME }}:${{ steps.meta.outputs.REPO_VERSION }}-${{ steps.meta.outputs.BUILD_NUMBER }} app.
