name: Build & Test App
on:
  push:
    branches:
      - 'dev/v[0-9]+.[0-9]+'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ gitea.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by Gitea!"
      - run: echo "🔎 The name of your branch is ${{ gitea.ref }} and your repository is ${{ gitea.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ gitea.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ gitea.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
  # release:
  #   runs-on: ubuntu-latest
  #   env: {} # TODO
  #   steps:
  #     - name: Login to Local ACR
  #       uses: docker/login-action@v2
  #       with:
  #         registry: ${{ variables.LOCAL_ACR_URL }}
  #         username: ${{ variables.LOCAL_ACR_USERNAME }}
  #         password: ${{ secrets.LOCAL_ACR_PASSWORD }}

  #     # TODO: Get meta info

  #     - name: Build & Push to Local ACR
  #       uses: docker/build-push-action@v4
  #       with:
  #         context: .
  #         file: ./Dockerfile
  #         platforms: |
  #           linux/amd64
  #           linux/arm64
  #         push: true
  #         tags: |
  #           # TODO: set tags here

  # test:
  #   runs-on: ubuntu-latest


# Dev run
# Build images and push to local ACR
# Run automated tests on it
#   - Perform API calls (grab list of alerts & jobs)
#   - Perform API call on alert tests
#   - Perform API call on job tests
# Notify user of successful/failed build&push&test


