name: Build/Push & Test App for Development
on:
  push:
    branches:
      - 'dev/v[0-9]+.[0-9]+'

env:
  IMAGE_BASE: ${{ vars.LOCAL_ACR_URL }}/${{ vars.LOCAL_ACR_USERNAME }}

jobs:
  release:
    name: Release (linux/${{ matrix.architecture }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64, arm64]
    steps:
      - name: Get Meta
        id: meta
        run: |
          echo REPO_NAME=$(echo ${GITHUB_REPOSITORY} | awk -F"/" '{print $2}') >> $GITHUB_OUTPUT
          echo REPO_VERSION=$(echo ${GITHUB_REF} | awk -F"/" '{print $4}') >> $GITHUB_OUTPUT
          echo BUILD_NUMBER=$(echo "`date +'%Y%m%d'`.${{ github.run_number }}") >> $GITHUB_OUTPUT

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Login to Local ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.LOCAL_ACR_URL }}
          username: ${{ vars.LOCAL_ACR_USERNAME }}
          password: ${{ secrets.LOCAL_ACR_PASSWORD }}

      - name: Install Dependencies
        run: |
          sudo apt update; sudo apt install qemu-user-static

      - name: Build & Push to Local ACR
        uses: docker/build-push-action@v6
        with:
          platforms: linux/${{ matrix.architecture }}
          push: true
          tags: |
            ${{ env.IMAGE_BASE }}/${{ steps.meta.outputs.REPO_NAME }}:${{ steps.meta.outputs.REPO_VERSION }}-${{ steps.meta.outputs.BUILD_NUMBER }}
            ${{ env.IMAGE_BASE }}/${{ steps.meta.outputs.REPO_NAME }}:${{ steps.meta.outputs.REPO_VERSION }}-dev-latest
            ${{ env.IMAGE_BASE }}/${{ steps.meta.outputs.REPO_NAME }}:dev-latest
        # run: |
        #   docker buildx build \
        #     --platform linux/amd64,linux/arm64 \
        #     --tag ${{ vars.LOCAL_ACR_URL }}/${{ vars.LOCAL_ACR_USERNAME }}/${{ steps.meta.outputs.REPO_NAME }}:${{ steps.meta.outputs.REPO_VERSION }}-${{ steps.meta.outputs.BUILD_NUMBER }} \
        #     --tag ${{ vars.LOCAL_ACR_URL }}/${{ vars.LOCAL_ACR_USERNAME }}/${{ steps.meta.outputs.REPO_NAME }}:${{ steps.meta.outputs.REPO_VERSION }}-dev-latest \
        #     --tag ${{ vars.LOCAL_ACR_URL }}/${{ vars.LOCAL_ACR_USERNAME }}/${{ steps.meta.outputs.REPO_NAME }}:dev-latest .
        #   docker push ${{ vars.LOCAL_ACR_URL }}/${{ vars.LOCAL_ACR_USERNAME }}/${{ steps.meta.outputs.REPO_NAME }}:${{ steps.meta.outputs.REPO_VERSION }}-${{ steps.meta.outputs.BUILD_NUMBER }}
        #   docker push ${{ vars.LOCAL_ACR_URL }}/${{ vars.LOCAL_ACR_USERNAME }}/${{ steps.meta.outputs.REPO_NAME }}:${{ steps.meta.outputs.REPO_VERSION }}-dev-latest
        #   docker push ${{ vars.LOCAL_ACR_URL }}/${{ vars.LOCAL_ACR_USERNAME }}/${{ steps.meta.outputs.REPO_NAME }}:dev-latest


  tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      #### Investigate why mounting docker-compose apps to gitea runner's /workspace causes permission errors ####
      # - name: Start Services & App
      #   env:
      #     HAWKUPS_ALERTS__example_webhook_alert__USER: ${{ secrets.HAWKUPS_PUSHOVER_USER }}
      #     HAWKUPS_ALERTS__example_webhook_alert__TOKEN: ${{ secrets.HAWKUPS_PUSHOVER_TOKEN }}
      #     HAWKUPS_ALERTS__example_pushover_alert__USER: ${{ secrets.HAWKUPS_PUSHOVER_USER }}
      #     HAWKUPS_ALERTS__example_pushover_alert__TOKEN: ${{ secrets.HAWKUPS_PUSHOVER_TOKEN }}
      #   run: bash local_run.sh standalone
      #### Investigate why mounting docker-compose apps to gitea runner's /workspace causes permission errors ####
      
      # - name: Perform Tests
      #   id: test_results
      #   run: |
      #     python3 -m pip install requests --break-system-packages > /dev/null 2>&1
      #     python3 tests/tests.py

      # - name: Stop if Tests Failed
      #   if: steps.test_results.outputs.results != 'success'
      #   run: |
      #     echo "Tests failed! Please view logs under 'Perform Tests' tasks."
      #     exit 1

      - name: Cleanup
        if: always()
        run: |
          docker compose stop
          docker compose rm -f
          rm -rf tests

  notify:
    name: Notify Developer
    runs-on: ubuntu-latest
    continue-on-error: true
    needs:
      - release
      - tests
    # uses: adam/gitea-workflows/.gitea/workflows/notify.yaml@main
    steps:
      - name: Get Meta
        id: meta
        run: |
          echo REPO_NAME=$(echo ${GITHUB_REPOSITORY} | awk -F"/" '{print $2}') >> $GITHUB_OUTPUT
          echo REPO_VERSION=$(echo ${GITHUB_REF} | awk -F"/" '{print $4}') >> $GITHUB_OUTPUT
          echo BUILD_NUMBER=$(echo "`date +'%Y%m%d'`.${{ github.run_number }}") >> $GITHUB_OUTPUT

      - name: Notify Developer of Success
        if: needs.release.result == 'success' && needs.tests.result == 'success'
        uses: umahmood/pushover-actions@main
        env:
          PUSHOVER_USER: ${{ secrets.PUSHOVER_USER }}
          PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
        with:
          title: Gitea DevOps
          message: ✅ Built/Pushed & Tested ${{ steps.meta.outputs.REPO_NAME }}:${{ steps.meta.outputs.REPO_VERSION }}-${{ steps.meta.outputs.BUILD_NUMBER }} app!

      - name: Notify Developer of Failure
        if: needs.release.result != 'success' || needs.tests.result != 'success'
        uses: umahmood/pushover-actions@main
        env:
          PUSHOVER_USER: ${{ secrets.PUSHOVER_USER }}
          PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
        with:
          title: Gitea DevOps
          message: ❌ Unable to build/push & test ${{ steps.meta.outputs.REPO_NAME }}:${{ steps.meta.outputs.REPO_VERSION }}-${{ steps.meta.outputs.BUILD_NUMBER }} app.
