name: Release App
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    env: {} # TODO
    steps:
      - name: Login to Local ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.LOCAL_ACR_URL }}
          username: ${{ vars.LOCAL_ACR_USERNAME }}
          password: ${{ secrets.LOCAL_ACR_PASSWORD }}

      # TODO: Get meta info

      - name: Build & Push to Local ACR
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            # TODO: set tags here
      
      - name: Login to Public ACR
        uses: docker/login-action@v2
        with:
          username: ${{ vars.PUBLIC_ACR_USERNAME }}
          password: ${{ secrets.PUBLIC_ACR_PASSWORD }}

      # TODO: Get meta info

      - name: Build & Push to Public ACR
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            # TODO: set tags here


# Prod run
# Build images and push to local ACR & public ACR
# Notify user of successful build&push
